# Generated by Django 3.1.4 on 2020-12-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_ingredient_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='ingriedients',
            new_name='ingredients',
        ),
    ]
